service: node-ts-lambda-api-template

provider:
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  stackName: lambda-api-template
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 30
  vpc:
    securityGroupIds:
      - ${ADD_SECURITY_GROUPS_HERE}
    subnetIds:
      - ${ADD_SUBNETS_HERE}      
  environment:
    AMAZON_ACCESS_KEY: ${env:AMAZON_ACCESS_KEY}
    AMAZON_SECRET_KEY: ${env:AMAZON_SECRET_KEY}
plugins:
  - serverless-offline
package: 
  artifact: template.zip

functions:
  event:
    handler: src/handler.handle
    name: lambda-api-template
    events:
      - http:
          path: /api/health
          method: get
          cors: true
